### ISSUE TITLE
Need to include installing and running napari in README

### ISSUE THREAD

**Issue by AlistairCurd** [oubino/napari-locpix#26]
I needed to `pip install napari` in addition to napari-locpix.

In fact, this did not allow me to run napari because Qt was missing, and I need to follow the instructions in the error message on trying run napari. I used `pip install -U 'napari[all]'`, one of the options at that point.

Then type in the command `napari` (should go in the README as well).

The napari opened with 'Annotate (napari-locpix)' in the Plugins menu! 🗡️ 
- Good to mention to find it there as well, though.

**Comment by oubino** [comment]
Added to README
